"use client"
import { useAccount } from "wagmi";

import Head from "next/head";
import styles from "../styles/Home.module.css";
// import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";

const supportedChains = ["11155111", "1"]

export default function Page() {
    const { isConnected, chain } = useAccount();
    console.log(isConnected);

    return (
        <div className={styles.container}>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* <Header /> */}
        {isConnected ? (
            <div>
            {supportedChains.includes(parseInt(chain?.id).toString()) ? (
                <div className="flex flex-row">
                <LotteryEntrance className="p-8" />
                </div>
            ) : (
                <div>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
            )}
            </div>
        ) : (
            <div>Please connect to a Wallet</div>
        )}
        </div>
    );
}
// "use client"

// import { useEvmNativeBalance, useEvmRunContractFunction } from "@moralisweb3/next"
// import { contractAddresses, abi } from "../constants";
// // import LotteryEntrance from "../components/LotteryEntrance";

// function HomePage() {
//     const address = "0xC653e99190F3c7351bd1094c8d7659D6cba50616"
//     const { data: nativeBalance } = useEvmNativeBalance({ 
//         chain: "11155111",
//         address
//     });
//     console.log(nativeBalance?.balance?.rawValue);
//     // const {
//     //     runContractFunction: enterRaffle,
//     //     data: enterTxResponse,
//     //     isLoading,
//     //     isFetching,
//     // } = useEvmRunContractFunction({
//     //     abi: abi,
//     //     address: "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
//     //     functionName: "enterRaffle",
//     //     msgValue: entranceFee,
//     //     params: {},
//     // });
//     const {
//         runContractFunction: getEntranceFee,
//         data: enterTxResponse,
//         error,
//         isFetching,
//     } = useEvmRunContractFunction({
//         chain: "0xaa36a7",
//         abi: abi,
//         address: "0x9D0cA3F4957E41f54D4813e5fbFC9a3ca2ba005e",
//         functionName: "getEntranceFee",
//         params: {},
//     })

//     console.log(enterTxResponse)
//     console.log(isFetching);
//     console.error(error);

//     return (
//         <div>
//             <h3>Wallet: {address}</h3>
//             <h3>Native Balance: {nativeBalance?.balance.ether} ETH</h3>
//         </div>
//     )
// }

// export default HomePage
